package com.example.electric_storage.infrastructure.transistor.repositories.additionalparameters.jfet;

import com.example.electric_storage.infrastructure.transistor.model.additionalparameters.JFETAdditionalTransistorParametersEntity;
import org.springframework.data.jpa.repository.JpaRepository;

interface JFETAdditionalTransistorParametersJpaRepository extends JpaRepository<JFETAdditionalTransistorParametersEntity, Long> {
}
