package com.example.electric_storage.infrastructure.transistor.repositories.additionalparameters.mosfet;

import com.example.electric_storage.infrastructure.transistor.model.additionalparameters.MOSFETAdditionalTransistorParametersEntity;
import org.springframework.data.jpa.repository.JpaRepository;

interface MOSFETAdditionalTransistorParametersJpaRepository extends JpaRepository<MOSFETAdditionalTransistorParametersEntity, Long> {
}
